### ISSUE TITLE
Files to exclude

### ISSUE THREAD

**Issue by atjuch** [atjuch/pantheon-migration#2]
Doing a test from GoDaddy managed WordPress to a Pantheon dev site was successful but allowed certain files to go through that need to be excluded.
#### Files that need to be excluded

**Under wp-content**

```
/wp-content/mu-plugins/gd-system-plugin/
/wp-content/mu-plugins/gd-system-plugin.php
/wp-content/w3tc-config/ 
/wp-content/object-cache.php
```
- Pantheon doesn't support W3 Total Cache plugin
- object-cache.php, this comes from other plugins which Pantheon doesn't support since it has it's own caching layer

**Under /code in SFTP server**

```
/code/gd-config.php
```

**Exclude from wp-config.php**

```
define('FS_METHOD', 'direct');
define('FS_CHMOD_DIR', 453);
define('FS_CHMOD_FILE', 388);
```

**Comment by atjuch** [comment]
These files are still showing up in `wp-config.php`

```
define('FS_METHOD', 'direct');
define('FS_CHMOD_DIR', 453);
define('FS_CHMOD_FILE', 388);
```

**Comment by akshatc** [comment]
Let us keep a separate bug for changes within wp-config. That has separate scope. Here we limit this to excluding files.

**Comment by atjuch** [comment]
Verified fixed and new issue posted.
